..FF
======================================================================
FAIL: test_parse_pdf (__main__.TestPDFParsing.test_parse_pdf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Documents/src/Big_Data/Data/Data_Miner_01/unittest/test_wordmatrix.py", line 25, in test_parse_pdf
    self.assertEqual(character_count, expected_character_count)
AssertionError: 0 != 2345

======================================================================
FAIL: test_save_word_matrix_report (__main__.TestPDFParsing.test_save_word_matrix_report)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Documents/src/Big_Data/Data/Data_Miner_01/unittest/test_wordmatrix.py", line 50, in test_save_word_matrix_report
    mock_file.return_value.__enter__.return_value.write.assert_called_once_with(expected_output)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/mock.py", line 944, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'write' to be called once. Called 12 times.
Calls: [call('Page 1:\n'),
 call('word1: 1\t'),
 call('word2: 1\t'),
 call('\n'),
 call('Page 2:\n'),
 call('word3: 1\t'),
 call('\n'),
 call('Page 3:\n'),
 call('word4: 1\t'),
 call('word5: 1\t'),
 call('word6: 1\t'),
 call('\n')].

----------------------------------------------------------------------
Ran 4 tests in 0.003s

FAILED (failures=2)
